# **1. cbind (Column Bind)**
Use cbind to combine vectors, matrices, or data frames by columns. Both datasets must have the same number of rows.

## **Create sample data frames**

In [1]:
df1 <- data.frame(ID = 1:3, Name = c("Alice", "Bob", "Charlie"))
df2 <- data.frame(Age = c(25, 30, 35), City = c("New York", "London", "Paris"))

## **Combine by columns**

In [2]:
combined_cols <- cbind(df1, df2)

In [3]:
combined_cols

  ID Name    Age City
1 1  Alice   25  New York
2 2  Bob     30  London
3 3  Charlie 35  Paris

# **2. rbind (Row Bind)**
Use rbind to combine data frames by rows. Both datasets must have the exact same column names and the same number of columns.

## **Create a new data frame with matching column names**

In [5]:
df3 <- data.frame(ID = 4:5, Name = c("David", "Eva"))

## **Combine by rows**

In [6]:
combined_rows <- rbind(df1, df3)

In [7]:
combined_rows

  ID Name
1 1  Alice
2 2  Bob
3 3  Charlie
4 4  David
5 5  Eva

# **3. merge (Database Joins)**
Use merge to combine data frames based on a common key column (or multiple columns).

First, let's create two data frames that share an EmpID column. Notice that Employee 1 is only in the first dataset, and Employee 5 is only in the second.

## **Sample Data for Merging**

In [8]:
employees <- data.frame(
  EmpID = c(1, 2, 3, 4),
  Name = c("Alice", "Bob", "Charlie", "David")
)

salaries <- data.frame(
  EmpID = c(2, 3, 4, 5),
  Salary = c(60000, 75000, 80000, 55000)
)

## **Default Merge (Inner Join)**

In [9]:
inner_join <- merge(employees, salaries, by = "EmpID")

In [10]:
inner_join

  EmpID Name    Salary
1 2     Bob     60000
2 3     Charlie 75000
3 4     David   80000

## **Merge with Left Join**

In [11]:
left_join <- merge(employees, salaries, by = "EmpID", all.x = TRUE)

In [12]:
left_join

  EmpID Name    Salary
1 1     Alice      NA
2 2     Bob     60000
3 3     Charlie 75000
4 4     David   80000

## **Advance merging**

Here are examples of how to merge data frames using more than one variable. You can accomplish this by passing a vector of column names to the by argument.

For these examples, let's use clinical data where multiple patients have multiple visits. We need to match records based on both PatientID and VisitNum

In [13]:
vitals <- data.frame(
  PatientID = c(101, 101, 102, 103),
  VisitNum  = c(1, 2, 1, 1),
  HeartRate = c(72, 75, 80, 68)
)

labs <- data.frame(
  PatientID = c(101, 101, 102, 104),
  VisitNum  = c(1, 3, 1, 1),
  WBC_Count = c(5.5, 6.2, 7.1, 4.8)
)

**Inner Join**

In [14]:
inner_join_multi <- merge(vitals, labs, by = c("PatientID", "VisitNum"))

inner_join_multi

  PatientID VisitNum HeartRate WBC_Count
1 101       1        72        5.5
2 102       1        80        7.1

Left Join

In [15]:
left_join_multi <- merge(vitals, labs, by = c("PatientID", "VisitNum"), all.x = TRUE)

left_join_multi

  PatientID VisitNum HeartRate WBC_Count
1 101       1        72        5.5
2 101       2        75         NA
3 102       1        80        7.1
4 103       1        68         NA